  name: Comnpila y Genera PDFMore actions
  
  on: 
    push:
      branches: main

  jobs:
    compila:
      runs-on: ubuntu-latest

      steps:
      - name: Tener copia local del repo
        uses: actions/checkout@v

      - name: Instalr .NET en el runner
        uses: actions/setup-dotnet@v4\
        with:
          dotnet-version: '9.0.x'

      - name: Instalar dependencias
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore
    
    crear-pdf:
      runs-on: ubuntu-latest
      steps: 
      - uses: actions/checkout@3
      - uses: baileyjm02/markdown-to-pdf@1
        with:
          input_dir: docs
          output_dir: pdfs
  
          build_html: true
      - uses: actions/upload-artifact@4
        with:
          name: docs
          path: pdfs
